"""initial_full_schema

Revision ID: 7c4df71e8ce8
Revises: 
Create Date: 2026-05-19 11:13:40.039894
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers
revision: str = '7c4df71e8ce8'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assumption_nodes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('node_type', sa.String(length=50), nullable=False),
    sa.Column('label', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('current_value', sa.Float(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('companies',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ticker', sa.String(length=20), nullable=False),
    sa.Column('cik', sa.String(length=20), nullable=True),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('exchange', sa.String(length=50), nullable=True),
    sa.Column('sector', sa.String(length=200), nullable=True),
    sa.Column('industry', sa.String(length=200), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('website', sa.String(length=500), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('market_cap', sa.BigInteger(), nullable=True),
    sa.Column('shares_outstanding', sa.BigInteger(), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.Column('last_refreshed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_companies_cik'), 'companies', ['cik'], unique=False)
    op.create_index(op.f('ix_companies_ticker'), 'companies', ['ticker'], unique=True)
    op.create_table('company_brain_snapshots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ticker', sa.String(length=20), nullable=False),
    sa.Column('snapshot_json', sa.JSON(), nullable=False),
    sa.Column('snapshot_date', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_company_brain_snapshots_ticker'), 'company_brain_snapshots', ['ticker'], unique=False)
    op.create_table('company_brains',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ticker', sa.String(length=20), nullable=False),
    sa.Column('profile_json', sa.JSON(), nullable=True),
    sa.Column('financials_json', sa.JSON(), nullable=True),
    sa.Column('valuation_json', sa.JSON(), nullable=True),
    sa.Column('signals_json', sa.JSON(), nullable=True),
    sa.Column('peers_json', sa.JSON(), nullable=True),
    sa.Column('risks_json', sa.JSON(), nullable=True),
    sa.Column('catalysts_json', sa.JSON(), nullable=True),
    sa.Column('ai_summary', sa.Text(), nullable=True),
    sa.Column('ai_what_changed', sa.Text(), nullable=True),
    sa.Column('ai_synthesis', sa.Text(), nullable=True),
    sa.Column('market_expectations_json', sa.JSON(), nullable=True),
    sa.Column('scenarios_json', sa.JSON(), nullable=True),
    sa.Column('health_score_json', sa.JSON(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('thesis_status', sa.String(length=50), nullable=True),
    sa.Column('last_refreshed', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_company_brains_ticker'), 'company_brains', ['ticker'], unique=True)
    op.create_table('company_intelligence_snapshots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ticker', sa.String(length=20), nullable=False),
    sa.Column('snapshot_payload_json', sa.JSON(), nullable=False),
    sa.Column('data_sources_json', sa.JSON(), nullable=True),
    sa.Column('source_confidence', sa.Float(), nullable=True),
    sa.Column('source_discrepancies_json', sa.JSON(), nullable=True),
    sa.Column('financial_version', sa.String(length=100), nullable=True),
    sa.Column('signal_version', sa.String(length=100), nullable=True),
    sa.Column('ai_version', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_company_intelligence_snapshots_ticker'), 'company_intelligence_snapshots', ['ticker'], unique=False)
    op.create_table('company_metrics',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ticker', sa.String(length=20), nullable=False),
    sa.Column('metric_key', sa.String(length=100), nullable=False),
    sa.Column('metric_value', sa.Float(), nullable=True),
    sa.Column('period', sa.String(length=20), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.Column('source_priority', sa.Integer(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ticker', 'metric_key', 'period', 'source', name='uq_company_metric')
    )
    op.create_index(op.f('ix_company_metrics_ticker'), 'company_metrics', ['ticker'], unique=False)
    op.create_index('ix_company_metrics_ticker_key', 'company_metrics', ['ticker', 'metric_key'], unique=False)
    op.create_table('daily_intelligence_snapshots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('snapshot_date', sa.Date(), nullable=False),
    sa.Column('snapshot_payload_json', sa.JSON(), nullable=False),
    sa.Column('macro_state', sa.String(length=100), nullable=True),
    sa.Column('top_signals_json', sa.JSON(), nullable=True),
    sa.Column('top_thesis_changes_json', sa.JSON(), nullable=True),
    sa.Column('top_portfolio_changes_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_daily_intelligence_snapshots_snapshot_date'), 'daily_intelligence_snapshots', ['snapshot_date'], unique=True)
    op.create_table('filings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ticker', sa.String(length=20), nullable=False),
    sa.Column('cik', sa.String(length=20), nullable=True),
    sa.Column('accession_number', sa.String(length=50), nullable=True),
    sa.Column('form_type', sa.String(length=20), nullable=False),
    sa.Column('filing_date', sa.Date(), nullable=False),
    sa.Column('report_date', sa.Date(), nullable=True),
    sa.Column('filing_url', sa.String(length=1000), nullable=True),
    sa.Column('raw_text_path', sa.String(length=500), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('accession_number')
    )
    op.create_index(op.f('ix_filings_ticker'), 'filings', ['ticker'], unique=False)
    op.create_table('internal_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('ticker', sa.String(length=20), nullable=True),
    sa.Column('payload_json', sa.JSON(), nullable=True),
    sa.Column('processed', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_events_type_processed', 'internal_events', ['event_type', 'processed'], unique=False)
    op.create_index(op.f('ix_internal_events_event_type'), 'internal_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_internal_events_ticker'), 'internal_events', ['ticker'], unique=False)
    op.create_table('macro_indicators',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('series_id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('series_id', 'date', name='uq_macro_series_date')
    )
    op.create_table('market_prices',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ticker', sa.String(length=20), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('open', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('high', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('low', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('close', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('adjusted_close', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('volume', sa.BigInteger(), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ticker', 'date', name='uq_market_prices_ticker_date')
    )
    op.create_index(op.f('ix_market_prices_ticker'), 'market_prices', ['ticker'], unique=False)
    op.create_index('ix_market_prices_ticker_date', 'market_prices', ['ticker', 'date'], unique=False)
    op.create_table('market_regime_snapshots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('regime', sa.String(length=50), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('factors_json', sa.JSON(), nullable=True),
    sa.Column('snapshot_date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('model_outputs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ticker', sa.String(length=20), nullable=False),
    sa.Column('model_type', sa.String(length=50), nullable=False),
    sa.Column('assumptions_json', sa.JSON(), nullable=True),
    sa.Column('output_json', sa.JSON(), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_model_output_ticker_type', 'model_outputs', ['ticker', 'model_type'], unique=False)
    op.create_index(op.f('ix_model_outputs_ticker'), 'model_outputs', ['ticker'], unique=False)
    op.create_table('narratives',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('relevance_score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('raw_api_responses',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('endpoint', sa.String(length=200), nullable=False),
    sa.Column('cache_key', sa.String(length=500), nullable=False),
    sa.Column('response_json', sa.JSON(), nullable=True),
    sa.Column('response_hash', sa.String(length=64), nullable=True),
    sa.Column('fetched_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_raw_api_responses_cache_key'), 'raw_api_responses', ['cache_key'], unique=True)
    op.create_table('signal_state_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ticker', sa.String(length=20), nullable=False),
    sa.Column('signal_type', sa.String(length=50), nullable=False),
    sa.Column('prior_signal_strength', sa.Float(), nullable=True),
    sa.Column('current_signal_strength', sa.Float(), nullable=True),
    sa.Column('change_direction', sa.String(length=20), nullable=True),
    sa.Column('interpretation', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_signal_history_ticker_type', 'signal_state_history', ['ticker', 'signal_type'], unique=False)
    op.create_index(op.f('ix_signal_state_history_ticker'), 'signal_state_history', ['ticker'], unique=False)
    op.create_table('state_change_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('prior_state_json', sa.JSON(), nullable=True),
    sa.Column('current_state_json', sa.JSON(), nullable=True),
    sa.Column('delta_summary', sa.Text(), nullable=True),
    sa.Column('why_it_matters', sa.Text(), nullable=True),
    sa.Column('severity', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_state_change_created', 'state_change_events', ['created_at'], unique=False)
    op.create_index('ix_state_change_entity', 'state_change_events', ['entity_type', 'entity_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('firebase_uid', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_firebase_uid'), 'users', ['firebase_uid'], unique=True)
    op.create_table('assumption_edges',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('source_node_id', sa.Integer(), nullable=False),
    sa.Column('target_node_id', sa.Integer(), nullable=False),
    sa.Column('relationship_type', sa.String(length=50), nullable=False),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['source_node_id'], ['assumption_nodes.id'], ),
    sa.ForeignKeyConstraint(['target_node_id'], ['assumption_nodes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('briefing_checklist_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('briefing_date', sa.Date(), nullable=False),
    sa.Column('item_key', sa.String(length=200), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('completed', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'briefing_date', 'item_key', name='uq_checklist_item')
    )
    op.create_index('ix_checklist_user_date', 'briefing_checklist_items', ['user_id', 'briefing_date'], unique=False)
    op.create_table('company_narratives',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ticker', sa.String(length=20), nullable=False),
    sa.Column('narrative_id', sa.Integer(), nullable=False),
    sa.Column('relevance', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['narrative_id'], ['narratives.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_company_narratives_ticker'), 'company_narratives', ['ticker'], unique=False)
    op.create_table('financial_statements',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ticker', sa.String(length=20), nullable=False),
    sa.Column('fiscal_year', sa.Integer(), nullable=False),
    sa.Column('fiscal_period', sa.String(length=10), nullable=False),
    sa.Column('period_end_date', sa.Date(), nullable=True),
    sa.Column('statement_type', sa.String(length=50), nullable=False),
    sa.Column('metric', sa.String(length=200), nullable=False),
    sa.Column('value', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('unit', sa.String(length=20), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.Column('filing_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['filing_id'], ['filings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_fin_stmt_ticker_type', 'financial_statements', ['ticker', 'statement_type'], unique=False)
    op.create_index('ix_fin_stmt_ticker_year', 'financial_statements', ['ticker', 'fiscal_year'], unique=False)
    op.create_index(op.f('ix_financial_statements_ticker'), 'financial_statements', ['ticker'], unique=False)
    op.create_table('narrative_snapshots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('narrative_id', sa.Integer(), nullable=False),
    sa.Column('strength', sa.Float(), nullable=True),
    sa.Column('snapshot_date', sa.Date(), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['narrative_id'], ['narratives.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('portfolios',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reports',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('ticker', sa.String(length=20), nullable=True),
    sa.Column('report_type', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('content_markdown', sa.Text(), nullable=True),
    sa.Column('sources_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('signals',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ticker', sa.String(length=20), nullable=False),
    sa.Column('signal_type', sa.String(length=50), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('direction', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('underlying_metrics_json', sa.JSON(), nullable=True),
    sa.Column('model_output_id', sa.Integer(), nullable=True),
    sa.Column('priority_score', sa.Float(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['model_output_id'], ['model_outputs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_signals_priority', 'signals', ['priority_score'], unique=False)
    op.create_index(op.f('ix_signals_ticker'), 'signals', ['ticker'], unique=False)
    op.create_index('ix_signals_ticker_type', 'signals', ['ticker', 'signal_type'], unique=False)
    op.create_table('thesis_boards',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('conviction_score', sa.Float(), nullable=True),
    sa.Column('time_horizon', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('watchlists',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('holdings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('portfolio_id', sa.Integer(), nullable=False),
    sa.Column('ticker', sa.String(length=20), nullable=False),
    sa.Column('shares', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('average_cost', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('portfolio_id', 'ticker', name='uq_holding_ticker')
    )
    op.create_table('portfolio_snapshots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('portfolio_id', sa.Integer(), nullable=False),
    sa.Column('snapshot_date', sa.DateTime(), nullable=False),
    sa.Column('total_value', sa.Numeric(precision=16, scale=4), nullable=True),
    sa.Column('risk_metrics_json', sa.JSON(), nullable=True),
    sa.Column('ai_commentary', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('thesis_assumptions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('thesis_board_id', sa.Integer(), nullable=False),
    sa.Column('ticker', sa.String(length=20), nullable=True),
    sa.Column('metric_key', sa.String(length=100), nullable=True),
    sa.Column('operator', sa.String(length=10), nullable=True),
    sa.Column('threshold_value', sa.Float(), nullable=True),
    sa.Column('assumption_text', sa.Text(), nullable=False),
    sa.Column('current_value', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('last_evaluated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['thesis_board_id'], ['thesis_boards.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_thesis_assumption_board', 'thesis_assumptions', ['thesis_board_id'], unique=False)
    op.create_table('thesis_conviction_snapshots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('thesis_board_id', sa.Integer(), nullable=False),
    sa.Column('conviction_score', sa.Float(), nullable=False),
    sa.Column('confidence_delta', sa.Float(), nullable=True),
    sa.Column('supporting_signals_json', sa.JSON(), nullable=True),
    sa.Column('weakening_signals_json', sa.JSON(), nullable=True),
    sa.Column('regime_alignment', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['thesis_board_id'], ['thesis_boards.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_conviction_snapshot_board', 'thesis_conviction_snapshots', ['thesis_board_id'], unique=False)
    op.create_table('thesis_stocks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('thesis_board_id', sa.Integer(), nullable=False),
    sa.Column('ticker', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['thesis_board_id'], ['thesis_boards.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('thesis_board_id', 'ticker', name='uq_thesis_stock_ticker')
    )
    op.create_table('thesis_timeline_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('thesis_board_id', sa.Integer(), nullable=False),
    sa.Column('ticker', sa.String(length=20), nullable=True),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('what_changed', sa.Text(), nullable=True),
    sa.Column('why_it_matters', sa.Text(), nullable=True),
    sa.Column('impacted_assumptions_json', sa.JSON(), nullable=True),
    sa.Column('severity', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['thesis_board_id'], ['thesis_boards.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('watchlist_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('watchlist_id', sa.Integer(), nullable=False),
    sa.Column('ticker', sa.String(length=20), nullable=False),
    sa.Column('added_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['watchlist_id'], ['watchlists.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('watchlist_id', 'ticker', name='uq_watchlist_ticker')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('watchlist_items')
    op.drop_table('thesis_timeline_events')
    op.drop_table('thesis_stocks')
    op.drop_index('ix_conviction_snapshot_board', table_name='thesis_conviction_snapshots')
    op.drop_table('thesis_conviction_snapshots')
    op.drop_index('ix_thesis_assumption_board', table_name='thesis_assumptions')
    op.drop_table('thesis_assumptions')
    op.drop_table('portfolio_snapshots')
    op.drop_table('holdings')
    op.drop_table('watchlists')
    op.drop_table('thesis_boards')
    op.drop_index('ix_signals_ticker_type', table_name='signals')
    op.drop_index(op.f('ix_signals_ticker'), table_name='signals')
    op.drop_index('ix_signals_priority', table_name='signals')
    op.drop_table('signals')
    op.drop_table('reports')
    op.drop_table('portfolios')
    op.drop_table('narrative_snapshots')
    op.drop_index(op.f('ix_financial_statements_ticker'), table_name='financial_statements')
    op.drop_index('ix_fin_stmt_ticker_year', table_name='financial_statements')
    op.drop_index('ix_fin_stmt_ticker_type', table_name='financial_statements')
    op.drop_table('financial_statements')
    op.drop_index(op.f('ix_company_narratives_ticker'), table_name='company_narratives')
    op.drop_table('company_narratives')
    op.drop_index('ix_checklist_user_date', table_name='briefing_checklist_items')
    op.drop_table('briefing_checklist_items')
    op.drop_table('assumption_edges')
    op.drop_index(op.f('ix_users_firebase_uid'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index('ix_state_change_entity', table_name='state_change_events')
    op.drop_index('ix_state_change_created', table_name='state_change_events')
    op.drop_table('state_change_events')
    op.drop_index(op.f('ix_signal_state_history_ticker'), table_name='signal_state_history')
    op.drop_index('ix_signal_history_ticker_type', table_name='signal_state_history')
    op.drop_table('signal_state_history')
    op.drop_index(op.f('ix_raw_api_responses_cache_key'), table_name='raw_api_responses')
    op.drop_table('raw_api_responses')
    op.drop_table('narratives')
    op.drop_index(op.f('ix_model_outputs_ticker'), table_name='model_outputs')
    op.drop_index('ix_model_output_ticker_type', table_name='model_outputs')
    op.drop_table('model_outputs')
    op.drop_table('market_regime_snapshots')
    op.drop_index('ix_market_prices_ticker_date', table_name='market_prices')
    op.drop_index(op.f('ix_market_prices_ticker'), table_name='market_prices')
    op.drop_table('market_prices')
    op.drop_table('macro_indicators')
    op.drop_index(op.f('ix_internal_events_ticker'), table_name='internal_events')
    op.drop_index(op.f('ix_internal_events_event_type'), table_name='internal_events')
    op.drop_index('ix_events_type_processed', table_name='internal_events')
    op.drop_table('internal_events')
    op.drop_index(op.f('ix_filings_ticker'), table_name='filings')
    op.drop_table('filings')
    op.drop_index(op.f('ix_daily_intelligence_snapshots_snapshot_date'), table_name='daily_intelligence_snapshots')
    op.drop_table('daily_intelligence_snapshots')
    op.drop_index('ix_company_metrics_ticker_key', table_name='company_metrics')
    op.drop_index(op.f('ix_company_metrics_ticker'), table_name='company_metrics')
    op.drop_table('company_metrics')
    op.drop_index(op.f('ix_company_intelligence_snapshots_ticker'), table_name='company_intelligence_snapshots')
    op.drop_table('company_intelligence_snapshots')
    op.drop_index(op.f('ix_company_brains_ticker'), table_name='company_brains')
    op.drop_table('company_brains')
    op.drop_index(op.f('ix_company_brain_snapshots_ticker'), table_name='company_brain_snapshots')
    op.drop_table('company_brain_snapshots')
    op.drop_index(op.f('ix_companies_ticker'), table_name='companies')
    op.drop_index(op.f('ix_companies_cik'), table_name='companies')
    op.drop_table('companies')
    op.drop_table('assumption_nodes')
    # ### end Alembic commands ###
