"""add_temporal_intelligence_evolution

Revision ID: 91b2f74ac7dd
Revises: 7c4df71e8ce8
Create Date: 2026-05-19 23:32:22.827445
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers
revision: str = '91b2f74ac7dd'
down_revision: Union[str, None] = '7c4df71e8ce8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('signal_temporal_analysis',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ticker', sa.String(length=20), nullable=False),
    sa.Column('signal_type', sa.String(length=100), nullable=False),
    sa.Column('persistence_score', sa.Float(), nullable=True),
    sa.Column('acceleration_score', sa.Float(), nullable=True),
    sa.Column('regime_sensitivity', sa.String(length=100), nullable=True),
    sa.Column('confidence_trend', sa.String(length=50), nullable=True),
    sa.Column('interpretation', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_signal_temporal_analysis_created_at'), 'signal_temporal_analysis', ['created_at'], unique=False)
    op.create_index(op.f('ix_signal_temporal_analysis_signal_type'), 'signal_temporal_analysis', ['signal_type'], unique=False)
    op.create_index(op.f('ix_signal_temporal_analysis_ticker'), 'signal_temporal_analysis', ['ticker'], unique=False)
    op.create_table('temporal_intelligence_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.String(length=100), nullable=False),
    sa.Column('prior_state_summary', sa.Text(), nullable=True),
    sa.Column('current_state_summary', sa.Text(), nullable=False),
    sa.Column('evolution_type', sa.String(length=50), nullable=False),
    sa.Column('acceleration_score', sa.Float(), nullable=True),
    sa.Column('importance_score', sa.Float(), nullable=True),
    sa.Column('why_it_matters', sa.Text(), nullable=True),
    sa.Column('implication_summary', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_temporal_intelligence_events_created_at'), 'temporal_intelligence_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_temporal_intelligence_events_entity_id'), 'temporal_intelligence_events', ['entity_id'], unique=False)
    op.create_index(op.f('ix_temporal_intelligence_events_entity_type'), 'temporal_intelligence_events', ['entity_type'], unique=False)
    op.create_index(op.f('ix_temporal_intelligence_events_evolution_type'), 'temporal_intelligence_events', ['evolution_type'], unique=False)
    op.create_index(op.f('ix_temporal_intelligence_events_importance_score'), 'temporal_intelligence_events', ['importance_score'], unique=False)
    op.create_table('thesis_evolution_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('thesis_board_id', sa.Integer(), nullable=False),
    sa.Column('prior_conviction', sa.Float(), nullable=True),
    sa.Column('current_conviction', sa.Float(), nullable=False),
    sa.Column('evolution_summary', sa.Text(), nullable=False),
    sa.Column('strongest_supporting_signal', sa.Text(), nullable=True),
    sa.Column('strongest_weakening_signal', sa.Text(), nullable=True),
    sa.Column('macro_alignment', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['thesis_board_id'], ['thesis_boards.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_thesis_evolution_history_created_at'), 'thesis_evolution_history', ['created_at'], unique=False)
    op.create_index(op.f('ix_thesis_evolution_history_thesis_board_id'), 'thesis_evolution_history', ['thesis_board_id'], unique=False)
    op.add_column('daily_intelligence_snapshots', sa.Column('macro_summary', sa.Text(), nullable=True))
    op.add_column('daily_intelligence_snapshots', sa.Column('top_signal_changes_json', sa.JSON(), nullable=True))
    op.add_column('daily_intelligence_snapshots', sa.Column('intelligence_feed_json', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('daily_intelligence_snapshots', 'intelligence_feed_json')
    op.drop_column('daily_intelligence_snapshots', 'top_signal_changes_json')
    op.drop_column('daily_intelligence_snapshots', 'macro_summary')
    op.drop_index(op.f('ix_thesis_evolution_history_thesis_board_id'), table_name='thesis_evolution_history')
    op.drop_index(op.f('ix_thesis_evolution_history_created_at'), table_name='thesis_evolution_history')
    op.drop_table('thesis_evolution_history')
    op.drop_index(op.f('ix_temporal_intelligence_events_importance_score'), table_name='temporal_intelligence_events')
    op.drop_index(op.f('ix_temporal_intelligence_events_evolution_type'), table_name='temporal_intelligence_events')
    op.drop_index(op.f('ix_temporal_intelligence_events_entity_type'), table_name='temporal_intelligence_events')
    op.drop_index(op.f('ix_temporal_intelligence_events_entity_id'), table_name='temporal_intelligence_events')
    op.drop_index(op.f('ix_temporal_intelligence_events_created_at'), table_name='temporal_intelligence_events')
    op.drop_table('temporal_intelligence_events')
    op.drop_index(op.f('ix_signal_temporal_analysis_ticker'), table_name='signal_temporal_analysis')
    op.drop_index(op.f('ix_signal_temporal_analysis_signal_type'), table_name='signal_temporal_analysis')
    op.drop_index(op.f('ix_signal_temporal_analysis_created_at'), table_name='signal_temporal_analysis')
    op.drop_table('signal_temporal_analysis')
    # ### end Alembic commands ###
